apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-devops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: enterprise-devops-app
  template:
    metadata:
      labels:
        app: enterprise-devops-app
    spec:
      containers:
        - name: enterprise-devops-app
          image: tummie/enterprise-devops-app:latest
          ports:
            - containerPort: 5000
