name: DevOps CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

    # Optimise the builds to be faster
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

    # Add security Checks
      - name: Install security scanner
        run: pip install bandit

      - name: Run security scan
        run: bandit -r app
      
      - name: Install dependency scanner
        run: pip install pip-audit

      - name: Scan dependencies for vulnerabilities
        run: pip-audit

      # Step 4: Clean Python cache
      - name: Clean __pycache__
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} +

      # Step 5: Set PYTHONPATH to project root
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      # Step 6: Run tests
      - name: Run tests
        run: pytest

      # step 7 Build and Push docker image to docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/enterprise-devops-app:dev .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/enterprise-devops-app:dev

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/enterprise-devops-app:dev
